version: '3.2'

services:
  drone-server:
    image: drone/drone:1.2.1

    ports:
      - 80:80
      - 443:443
    extra_hosts:
      - postgres.whyservices.net:10.0.0.154
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    env_file:
      - production.env
